#include <stdio.h>
#include <stdlib.h>

// Forward declarations generated by Lemon
void *ParseAlloc(void *(*mallocProc)(size_t));
void Parse(void *yyp, int yymajor, const char *yytoken, void *pArg);
void ParseFree(void *pArg, void (*freeProc)(void*));

// Include the token header generated by Lemon
#include "grammar.h"

int main() {
    void* parser = ParseAlloc(malloc);
    const char* input = "READ table";

    /*
    // Pass the STRING token and its payload to the parser
    Parse(parser, READ, "READ", NULL);

    // Pass the STRING token and its payload to the parser
    Parse(parser, STRING, "STRING", NULL);*/

    /**/
    // Pass the STRING token and its payload to the parser
    Parse(parser, WRITE, "WRITE", NULL);

    // Pass the STRING token and its payload to the parser
    Parse(parser, STRING, "new_table", NULL);
    
    // Pass the STRING token and its payload to the parser
    Parse(parser, INSTRUCTIONS, "INSTRUCTIONS", NULL);

    // Pass the STRING token and its payload to the parser
    Parse(parser, STRING, "step_1", NULL);
    
    // Pass the STRING token and its payload to the parser
    Parse(parser, INGREDIENTS, "INGREDIENTS", NULL);

    // Pass the STRING token and its payload to the parser
    Parse(parser, STRING, "cherry_vodka", NULL);

    // Pass the STRING token and its payload to the parser
    Parse(parser, STRING, "coke", NULL);
    
    
    // Signal End-of-Input (token ID 0)
    Parse(parser, 0, NULL, NULL);

    ParseFree(parser, free);
    return 0;
}


